name: Go Test and Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Build and Test
      run: |
        go mod download
        go build -v ./...
        go test -v ./...
